leftnav:
- identifier: 5e8b7316-9e91-9831-7308-1878ea2d54a3
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: f7b4512e-0bfe-04d2-5787-4e36d41e1974
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: 645568e2-8f3b-8673-f775-d5e565520028
  name: Readings
  pageRef: /pages/readings
  weight: 30
- identifier: e92cbec9-cfc1-08c2-4f45-41249c93f828
  name: Lecture Notes
  pageRef: /pages/lecture-notes
  weight: 40
- identifier: 4512250d-75b9-eea0-4943-9b0898e8ee1a
  name: Assignments
  pageRef: /pages/assignments
  weight: 50
